version: 4
jobs:
    build:
        branches:
            only:
                - master123
        docker:
            - image: yarnpkg/node-yarn
        steps:
            - checkout
            - restore_cache:
                keys:
                  - node_modules-v1-{{ checksum "tutorial/react-native-2/gamezone/yarn.lock" }}
            - run:
                name: Greeting
                command: |
                        echo this is demo CircleCI && npm install && yarn install
            - save_cache:
                key: node_modules-v1-{{ checksum "tutorial/react-native-2/gamezone/yarn.lock" }}
                paths:
                    - node_modules